In [1]:
import os, math, itertools
import numpy as np

In [2]:
from generate_test_sample import generate_sample
from sample_reader import SampleReader

In [3]:
samples_fv = SampleReader().read('/Users/andrewbzikadze/chihua/datasets/AbVitro/flu_time_course/FV/', ['25'])
samples_gmc = SampleReader().read('/Users/andrewbzikadze/chihua/datasets/AbVitro/flu_time_course/GMC/', ['8'])
samples_ido = SampleReader().read('/Users/andrewbzikadze/chihua/datasets/AbVitro/flu_time_course/IDO/')
samples_age = SampleReader().read('/Users/andrewbzikadze/chihua/datasets/age/')
samples_paired = SampleReader().read('/Users/andrewbzikadze/chihua/datasets/AbVitro/paired/')

In [4]:
from shm_kmer_model_estimator import ShmKmerModelEstimator

In [30]:
estimator = ShmKmerModelEstimator()
est_model = estimator.estimate_models_of_one_type((#samples_age,
                                                   #samples_ido,
                                                   #samples_fv,
                                                   samples_gmc,
                                                   samples_paired
                                                  ),
                                                  chains=['IGH', 'IGK', 'IGL'])

NoKNeighbours: IGH
NoKNeighbours: IGK
NoKNeighbours: IGL
Trivial: IGH
Trivial: IGK
Trivial: IGL


In [31]:
est_model['NoKNeighbours']['IGK']

beta_shape1  beta_shape2    dir_shape1   dir_shape2    dir_shape3  \
AAAAA    14.883947   524.115840      9.524400    11.457888      2.202404   
AAAAC     4.714259    89.543922      6.027751    19.057985      2.106033   
AAAAG    12.362007   202.912625     13.623920     4.275669      2.316022   
AAAAT    12.143571   134.778974     10.340163    18.148272      3.115601   
AAACA     6.448083    99.447081      4.899089    13.440550      5.046643   
AAACC    37.482542   554.526769     17.211704   135.785338     10.908592   
AAACG     0.066978    25.416047      1.666667     0.666667      0.666667   
AAACT     1.514663    26.494915      1.375733     1.634373      1.532660   
AAAGA    39.502133  1028.528599      8.849149    16.730126      2.085852   
AAAGC    15.152594   314.686507     24.164498    49.908382     10.420042   
AAAGG     8.427889   185.869175      6.735612     7.610690      3.011557   
AAAGT    38.278476   856.378661     12.623794    40.882046      5.263467   
AAATA     0.000000     1.000000      1.000000     1.000000      1.000000   
AAATC    16.195922  1603.336741      8.704819    11.978094      3.242746   
AAATG    11.312070   138.951243      4.523805     9.887792      2.959384   
AAATT     8.674287   333.069844      6.417105    11.706919      4.016353   
AACAA    12.014614    98.724072      5.610598     5.271113     12.052412   
AACAC     6.552314   125.577104      8.428539     4.857925     15.492909   
AACAG    30.912064   723.066225     28.984621    46.766537     31.925280   
AACAT     7.374824   197.784426     12.042098     3.993728     14.189989   
AACCA    32.454560   665.654687      8.932434    23.657091     15.082651   
AACCC     0.166846     1.008755     23.540979    70.317722     47.088543   
AACCG     6.162057    24.413735      1.920060    12.165060      7.961736   
AACCT    12.942260   383.401555     16.883551    30.679569     21.148507   
AACGA     0.000000     1.000000      1.000000     1.000000      1.000000   
AACGC          NaN          NaN      1.000000     1.000000      1.000000   
AACGG     7.028921   338.458669   1596.356080  1287.776310    552.833496   
AACGT     3.470073    66.276199      7.206684     3.715734     14.878536   
AACTA    25.261773   265.648150      9.683410    13.725948     44.122315   
AACTC     6.573665   155.515250      3.786330     7.488552      3.946670   
...            ...          ...           ...          ...           ...   
TTGAG     1.745801    32.184350      1.507985     2.416907      0.973224   
TTGAT    85.502551  4777.238243      4.864141     4.211273      5.642470   
TTGCA    23.362115   832.882958     51.576878     6.575843     15.848597   
TTGCC     1.934637   107.856620    192.906464   312.363341    474.398363   
TTGCG          NaN          NaN      1.000000     1.000000      1.000000   
TTGCT    16.223501   505.416235      6.507371     5.417079      5.465566   
TTGGA    13.174344   401.616639     22.026102     7.829651      7.952165   
TTGGC     2.039987    66.333787  23088.586426  8551.075307  15074.860438   
TTGGG     5.168174   224.620615      4.211373     5.967585      6.061373   
TTGGT     2.149087   145.203958     38.578505    22.350294     33.056349   
TTGTA    12.421217   207.937576      7.936318    11.336398      2.898004   
TTGTC     4.675600   154.660868      5.632755    10.860459      8.776672   
TTGTG    12.701578   839.370049     10.907338    21.871451     18.291305   
TTGTT     0.000000     1.000000      1.000000     1.000000      1.000000   
TTTAA     3.723986   390.609142     13.776976    19.837712     19.870027   
TTTAC    17.574045   347.570442      4.900650    20.630327      6.257942   
TTTAG     3.793480   166.635558      2.951498     6.562434     12.573419   
TTTAT     2.310390    77.126489      2.407291     3.685240      7.144076   
TTTCA     4.947207   320.472344      9.599685    10.360529     13.355320   
TTTCC     5.206199   421.486286     23.030947    18.765371     37.192800   
TTTCG          NaN          NaN      1.000000     1.000

In [32]:
np.mean(est_model['NoKNeighbours']['IGH']['success_optim_beta'])

0.93359375

In [33]:
samples_paired['NoKNeighbours']['IGH'][:,6,:]

array([[21,  0,  0,  0]])

In [34]:
def apply_to_datasets(datasets, func):
    result = dict.fromkeys(datasets)
    for strategy in datasets:
        result[strategy] = dict.fromkeys(datasets[strategy])
        for chain_type in datasets[strategy]:
            result[strategy][chain_type] = \
            func(datasets[strategy][chain_type])
    return result

In [35]:
apply_to_datasets(est_model, (lambda x: x.isnull().any(axis=1).mean()))

{'NoKNeighbours': {'IGH': 0.0234375, 'IGK': 0.087890625, 'IGL': 0.0458984375},
 'Trivial': {'IGH': 0.009765625, 'IGK': 0.0791015625, 'IGL': 0.041015625}}

In [36]:
apply_to_datasets(est_model, (lambda x: x['success_optim_beta'].mean()))

{'NoKNeighbours': {'IGH': 0.93359375, 'IGK': 0.9462890625, 'IGL': 0.95703125},
 'Trivial': {'IGH': 0.98046875, 'IGK': 0.982421875, 'IGL': 0.98828125}}

In [37]:
apply_to_datasets(est_model, (lambda x: x['success_optim_dir'].mean()))

{'NoKNeighbours': {'IGH': 0.8974609375,
  'IGK': 0.9404296875,
  'IGL': 0.9501953125},
 'Trivial': {'IGH': 0.93359375, 'IGK': 0.951171875, 'IGL': 0.9619140625}}

In [13]:
test_sample = generate_sample(sample_size=1000,
                number_samples=20,
                real_beta_shape1=3,
                real_beta_shape2=15,
                real_dir_lambda=[10, 11, 12],
                nonmutated_ind=0)

print(test_sample)

np.mean(1 - test_sample[:,0] / np.sum(test_sample, axis=1, dtype=float))

[[981   7   7   5]
 [722 105  89  84]
 [831  33  40  96]
 [817  59  61  63]
 [838  43  52  67]
 [805  59  82  54]
 [892  35  28  45]
 [796  69  54  81]
 [842  38  57  63]
 [809  64  38  89]
 [774 100  26 100]
 [887  36  31  46]
 [768  69  94  69]
 [828  40  71  61]
 [913  23  21  43]
 [784  77  79  60]
 [919  24  25  32]
 [744  96  71  89]
 [739  80  47 134]
 [829  50  51  70]]


0.1741